version: '3.7'
services:

  redis-stack:
    image: redis/redis-stack-server:latest
    networks:
      - redis-network

  redisinsight:
    image: redislabs/redisinsight:latest
    networks:
      - redis-network
    depends_on:
      - redis-stack

  envoy:
    image: bitnami/envoy
    volumes:
      - ./envoy.yaml:/opt/bitnami/envoy/conf/envoy.yaml
    ports:
      - "8005:8005"
      - "10000:10000"
    depends_on:
      - redisinsight
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
