version: "3.8"
services:
  redis-stack:
    image: redis/redis-stack-server
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    restart: unless-stopped
    environment:
      - RIPORT=${RIPORT:-8001}
      - RITRUSTEDORIGINS=http://localhost:9000
      - RIPROXYENABLE=t
      - RIPROXYPATH=${RIPROXYPATH:-/apps/v1/}
    ports:
      - "8001:8001"
    depends_on:
      redis-stack:
        condition: service_healthy
    networks:
      - redis-network

  redisinsight-v2:
    image: redislabs/redisinsight:latest
    pull_policy: if_not_present
    environment:
      - RI_PROXY_PATH=${RI_PROXY_PATH:-apps/v2}
    ports:
      - "5540:5540"
    depends_on:
      - redis-stack
    networks:
      - redis-network


  nginx-subpath-proxy:
    image: nginx
    volumes:
      - ./nginx-subpath-proxy.conf.template:/etc/nginx/templates/nginx-subpath-proxy.conf.template
    ports:
      - "${NGINX_PORT:-9000}:${NGINX_PORT:-9000}"
    environment:
      - NGINX_PORT=${NGINX_PORT:-9000}
      - FORWARD_HOST=redisinsight
      - FORWARD_PORT=${RIPORT:-8001}
      - NGINX_PROXY_PATH=${RIPROXYPATH:-/apps/v1/}
      - FORWARD_V2_HOST=redisinsight-v2
      - FORWARD_V2_PORT=${RIPORT:-5540}
      - NGINX_V2_PROXY_PATH=${RI_PROXY_PATH:-apps/v2}
    command:
      - bash
      - -c
      - |
        printf "Visit <a href=\"$$NGINX_PROXY_PATH\">$$NGINX_PROXY_PATH</a> for RedisInsight v1 and <a href=\"/$$NGINX_V2_PROXY_PATH/\">$$NGINX_V2_PROXY_PATH</a> for RedisInsight v2" > /etc/nginx/index.html
        /docker-entrypoint.sh nginx -g "daemon off;"
    depends_on:
      - redisinsight
    networks:
      - redis-network

  redisinsight-redis-setup:
    image: alpine
    environment:
      - RIPORT=${RIPORT:-8001}
    command:
      - sh
      - -c
      - |
        apk add curl
        echo "Adding redis-stack...."
        wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- redisinsight:$$RIPORT -- echo Redisinsight is up
        curl -s -X "POST" "http://redisinsight:$$RIPORT/api/instance/"   -H "Content-Type: application/json; charset=utf-8" -d '{"host": "redis-stack","name": "redis-stack","connectionType": "STANDALONE","port": 6379}'
    networks:
      - redis-network
    depends_on:
      redis-stack:
        condition: service_healthy

networks:
  redis-network:
    driver: bridge
