version: '3.7'
services:

  redis-stack:
    image: redis/redis-stack-server:latest
    networks:
      - redis-network

  redis-insight:
    image: redislabs/redisinsight:latest
    networks:
      - redis-network
    depends_on:
      - redis-stack

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - redis-insight
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
