version: "3.7"
services:
  redis-stack:
    image: redis/redis-stack-server
    networks:
      - redis-network

  redisinsight:
    image: redislabs/redisinsight
    environment:
      - RIPORT=${RIPORT-8001}
    ports:
      - "${RIPORT-8001}:${RIPORT-8001}"
    depends_on:
      - redis-stack
    networks:
      - redis-network

  nginx-basicauth:
    image: nginx
    volumes:
      - ./nginx-basic-auth.conf.template:/etc/nginx/templates/nginx-basic-auth.conf.template
    ports:
      - "${NGINX_PORT-9000}:${NGINX_PORT-9000}"
    environment:
      - FORWARD_HOST=redisinsight
      - FORWARD_PORT=${RIPORT-8001}
      - NGINX_PORT=${NGINX_PORT-9000}
      - BASIC_USERNAME=${BASIC_USERNAME-redis}
      - BASIC_PASSWORD=${BASIC_PASSWORD-password}
    command:
      - bash
      - -c
      - printf "$$BASIC_USERNAME:$$(openssl passwd -crypt $$BASIC_PASSWORD)\n" >> /etc/nginx/.htpasswd && /docker-entrypoint.sh nginx -g "daemon off;"
    depends_on:
      - redisinsight
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
